Vet clinic database: add "join table" for visits
Ibtisam34/Vet-clinic-database pull request #5
Opened 2023-01-31 15:07 UTC by Ibtisam34

- [ ]  In this project, I had to add some many-to-many relationships and write more complex queries to use them to answer questions.

2023-01-31 15:59 UTC, mikethreels requested changes
Hi Riyana, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 15:59 UTC, mikethreels commented on queries.sql
> +LIMIT 1;
- [ ] the last animal seen by William Tatcher should be blossom, however, your query returns an empty row.

2023-01-31 15:59 UTC, mikethreels commented on queries.sql
> +WHERE ve.name = 'Stephanie Mendez';
- [ ] Stephanie Mendez has seen 4 different animals according to the information provided by the assignment, your query only returns 2 please double-check.

2023-01-31 15:59 UTC, mikethreels commented on queries.sql
> +GROUP BY ve.name;
- [ ] there is no print screen of the outcome of this query please make sure to add it as well.

2023-01-31 15:59 UTC, mikethreels commented on queries.sql
> +WHERE ve.name = 'Stephanie Mendez' AND v.date BETWEEN '2020-04-01' AND '2020-08-30';
- [ ] this query should return Agumon and Blossom according to the provided information, please double-check.

2023-01-31 15:59 UTC, mikethreels commented on queries.sql
> +LIMIT 1;
- [ ] according to the provided information the outcome of this query should be Boarmon, your query returns Squirtle, please check and correct.

2023-01-31 15:59 UTC, mikethreels commented on queries.sql
> +LIMIT 1;
- [ ] the first visit of Maisy Smith is Boarmon according to the provided information, this query returns Charmander, please check and correct.

2023-01-31 15:59 UTC, mikethreels commented on queries.sql
> +LIMIT 1;
- [ ] it seems like the data inserted into the tables might not be entirely correct, as according to the provided data Devimon visited Stephany Mendez on 2021-05-04, your query returns Angemon visiting Maisy Smith.

2023-01-31 15:59 UTC, mikethreels commented on queries.sql
> +WHERE sp.id IS NULL;
- [ ] Maisy Smith is the only vet without specialisation and she was visited 9 times, your query returns 5, please check and correct.

2023-02-01 09:05 UTC, m05e5 approved these changes
**Hi @Ibtisam34 

You did great. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights
✔️ Descriptive PR 

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-02-01 09:10 UTC, merged